version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: node
    depends_on:
      - mongo
    restart: always
    ports:
      - "4000:4000"
